package dev.cortexos.mcp.model

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 * A tool definition registered with the Anthropic API.
 * Maps directly to the API's tool array format.
 *
 * @param name        Dot-namespaced identifier: "contacts.search", "sms.send", etc.
 * @param description Human-readable description the LLM uses to decide when to call this tool.
 * @param inputSchema JSON Schema object describing the tool's input parameters.
 */
@Serializable
data class Tool(
    val name: String,
    val description: String,
    val inputSchema: JsonObject
)

/**
 * A completed tool_use block extracted from the Anthropic SSE stream.
 * Emitted by [dev.cortexos.llm.AnthropicApiClient] as [dev.cortexos.llm.model.StreamEvent.ToolUseBlock]
 * once the full input JSON has been accumulated from streaming deltas.
 *
 * @param id    Opaque identifier generated by the API (e.g. "toolu_01Xyz…").
 *              Must be echoed back in the corresponding tool_result message.
 * @param name  The tool name called (e.g. "contacts.search").
 * @param input Fully parsed JSON arguments for the tool call.
 */
data class ToolUseBlock(
    val id: String,
    val name: String,
    val input: JsonObject
)

/**
 * The result of executing a single [ToolUseBlock] via an [dev.cortexos.mcp.McpServerProvider].
 *
 * @param toolUseId Mirrors [ToolUseBlock.id] so the API can match result to call.
 * @param content   Plain-text or JSON-stringified result to feed back to the model.
 * @param isError   If true, [content] contains an error description rather than data.
 */
data class ToolResult(
    val toolUseId: String,
    val content: String,
    val isError: Boolean = false
)
